version: '3'

services:
  api:
    container_name: flask_app
    build:
      context: ./.
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./:/flask3
    command: python3 main.py

    depends_on:
      - mysql

  mysql:
    container_name: flask_mysql
    image: mysql:8.0
    ports:
      - 3333:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/my.cnf
    env_file:
      - .env
