version: '3'

networks:
  my-networks:
    driver: bridge

volumes:
  dir-site:
    driver_opts:
      device: /home/admin/Desktop/Tutorials/mycode3
      type: bind
      o: bind

services:
  my-mysql:
    container_name: test_mysql
    image: 'mysql:8.0'
    # restart: always
    networks:
      - my-networks
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=linh
      - MYSQL_ROOT_PASSWORD=pass

  my-api:
    container_name: test_api
    build:
      context: ./.
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my-networks
    volumes:
      - ./api/:/app/
    ports:
      - "8989:8989"
    depends_on:
      - my-mysql
